'use strict';var aa,ba=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ca=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function l(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if(typeof Object.setPrototypeOf=="function")fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function p(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ga=b.prototype}function la(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function q(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:la(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ma(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function r(){this.D=!1;this.o=null;this.j=void 0;this.g=1;this.m=this.u=0;this.H=this.i=null}function na(a){if(a.D)throw new TypeError("Generator is already running");a.D=!0}
r.prototype.G=function(a){this.j=a};function oa(a,b){a.i={X:b,isException:!0};a.g=a.u||a.m}r.prototype.getNextAddressJsc=function(){return this.g};r.prototype.getYieldResultJsc=function(){return this.j};r.prototype.return=function(a){this.i={return:a};this.g=this.m};r.prototype["return"]=r.prototype.return;r.prototype.K=function(a){this.i={F:a};this.g=this.m};r.prototype.jumpThroughFinallyBlocks=r.prototype.K;r.prototype.h=function(a,b){this.g=b;return{value:a}};r.prototype.yield=r.prototype.h;
r.prototype.N=function(a,b){a=q(a);var c=a.next();ma(c);if(c.done)this.j=c.value,this.g=b;else return this.o=a,this.h(c.value,b)};r.prototype.yieldAll=r.prototype.N;r.prototype.F=function(a){this.g=a};r.prototype.jumpTo=r.prototype.F;r.prototype.C=function(){this.g=0};r.prototype.jumpToEnd=r.prototype.C;r.prototype.A=function(a,b){this.u=a;b!=void 0&&(this.m=b)};r.prototype.setCatchFinallyBlocks=r.prototype.A;r.prototype.M=function(a){this.u=0;this.m=a||0};r.prototype.setFinallyBlock=r.prototype.M;
r.prototype.B=function(a,b){this.g=a;this.u=b||0};r.prototype.leaveTryBlock=r.prototype.B;r.prototype.v=function(a){this.u=a||0;a=this.i.X;this.i=null;return a};r.prototype.enterCatchBlock=r.prototype.v;r.prototype.I=function(a,b,c){c?this.H[c]=this.i:this.H=[this.i];this.u=a||0;this.m=b||0};r.prototype.enterFinallyBlock=r.prototype.I;
r.prototype.L=function(a,b){b=this.H.splice(b||0)[0];(b=this.i=this.i||b)?b.isException?this.g=this.u||this.m:b.F!=void 0&&this.m<b.F?(this.g=b.F,this.i=null):this.g=this.m:this.g=a};r.prototype.leaveFinallyBlock=r.prototype.L;r.prototype.J=function(a){return new pa(a)};r.prototype.forIn=r.prototype.J;function pa(a){this.i=a;this.g=[];for(var b in a)this.g.push(b);this.g.reverse()}pa.prototype.h=function(){for(;this.g.length>0;){var a=this.g.pop();if(a in this.i)return a}return null};
pa.prototype.getNext=pa.prototype.h;function qa(a){this.g=new r;this.h=a}function ra(a,b){na(a.g);var c=a.g.o;if(c)return sa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return ta(a)}function sa(a,b,c,d){try{var e=b.call(a.g.o,c);ma(e);if(!e.done)return a.g.D=!1,e;var f=e.value}catch(g){return a.g.o=null,oa(a.g,g),ta(a)}a.g.o=null;d.call(a.g,f);return ta(a)}
function ta(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.D=!1,{value:b.value,done:!1}}catch(c){a.g.j=void 0,oa(a.g,c)}a.g.D=!1;if(a.g.i){b=a.g.i;a.g.i=null;if(b.isException)throw b.X;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ua(a){this.next=function(b){na(a.g);a.g.o?b=sa(a,a.g.o.next,b,a.g.G):(a.g.G(b),b=ta(a));return b};this.throw=function(b){na(a.g);a.g.o?b=sa(a,a.g.o["throw"],b,a.g.G):(oa(a.g,b),b=ta(a));return b};this.return=function(b){return ra(a,b)};this[Symbol.iterator]=function(){return this}}function va(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
function t(a){return va(new ua(new qa(a)))}l("Reflect.setPrototypeOf",function(a){return a?a:ka?function(b,c){try{return ka(b,c),!0}catch(d){return!1}}:null});
l("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
l("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");ca(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return xa(la(this))}});return a});function xa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
l("Promise",function(a){function b(g){this.h=0;this.i=void 0;this.g=[];this.u=!1;var h=this.j();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(this.g==null){this.g=[];var h=this;this.i(function(){h.m()})}this.g.push(g)};var e=ea.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.m=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(m){this.j(m)}}}this.g=null};c.prototype.j=function(g){this.i(function(){throw g;})};b.prototype.j=function(){function g(m){return function(n){k||(k=!0,m.call(h,n))}}var h=this,k=!1;return{resolve:g(this.D),reject:g(this.m)}};b.prototype.D=function(g){if(g===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.H(g);else{a:switch(typeof g){case "object":var h=g!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.C(g):this.o(g)}};
b.prototype.C=function(g){var h=void 0;try{h=g.then}catch(k){this.m(k);return}typeof h=="function"?this.I(h,g):this.o(g)};b.prototype.m=function(g){this.v(2,g)};b.prototype.o=function(g){this.v(1,g)};b.prototype.v=function(g,h){if(this.h!=0)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.h);this.h=g;this.i=h;this.h===2&&this.G();this.B()};b.prototype.G=function(){var g=this;e(function(){if(g.A()){var h=ea.console;typeof h!=="undefined"&&h.error(g.i)}},1)};b.prototype.A=
function(){if(this.u)return!1;var g=ea.CustomEvent,h=ea.Event,k=ea.dispatchEvent;if(typeof k==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof h==="function"?g=new h("unhandledrejection",{cancelable:!0}):(g=ea.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return k(g)};b.prototype.B=function(){if(this.g!=null){for(var g=0;g<this.g.length;++g)f.h(this.g[g]);this.g=null}};var f=new c;
b.prototype.H=function(g){var h=this.j();g.R(h.resolve,h.reject)};b.prototype.I=function(g,h){var k=this.j();try{g.call(h,k.resolve,k.reject)}catch(m){k.reject(m)}};b.prototype.then=function(g,h){function k(x,A){return typeof x=="function"?function(F){try{m(x(F))}catch(C){n(C)}}:A}var m,n,v=new b(function(x,A){m=x;n=A});this.R(k(g,m),k(h,n));return v};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.R=function(g,h){function k(){switch(m.h){case 1:g(m.i);break;case 2:h(m.i);break;
default:throw Error("Unexpected state: "+m.h);}}var m=this;this.g==null?f.h(k):this.g.push(k);this.u=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var m=q(g),n=m.next();!n.done;n=m.next())d(n.value).R(h,k)})};b.all=function(g){var h=q(g),k=h.next();return k.done?d([]):new b(function(m,n){function v(F){return function(C){x[F]=C;A--;A==0&&m(x)}}var x=[],A=0;do x.push(void 0),A++,d(k.value).R(v(x.length-1),n),k=h.next();while(!k.done)})};
return b});l("Object.setPrototypeOf",function(a){return a||ka});function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var ya=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)u(d,e)&&(a[e]=d[e])}return a};l("Object.assign",function(a){return a||ya});
l("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=q(k);for(var m;!(m=k.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(k){var m=typeof k;return m==="object"&&k!==null||m==="function"}function e(k){if(!u(k,g)){var m=new c;ca(k,g,{value:m})}}function f(k){var m=Object[k];m&&(Object[k]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),m=Object.seal({}),
n=new a([[k,2],[m,3]]);if(n.get(k)!=2||n.get(m)!=3)return!1;n.delete(k);n.set(m,4);return!n.has(k)&&n.get(m)==4}catch(v){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,m){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,g))throw Error("WeakMap key fail: "+k);k[g][this.g]=m;return this};b.prototype.get=function(k){return d(k)&&u(k,g)?k[g][this.g]:void 0};b.prototype.has=function(k){return d(k)&&u(k,
g)&&u(k[g],this.g)};b.prototype.delete=function(k){return d(k)&&u(k,g)&&u(k[g],this.g)?delete k[g][this.g]:!1};return b});
l("Map",function(a){function b(){var h={};return h.previous=h.next=h.head=h}function c(h,k){var m=h[1];return xa(function(){if(m){for(;m.head!=h[1];)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:k(m)};m=null}return{done:!0,value:void 0}})}function d(h,k){var m=k&&typeof k;m=="object"||m=="function"?f.has(k)?m=f.get(k):(m=""+ ++g,f.set(k,m)):m="p_"+k;var n=h[0][m];if(n&&u(h[0],m))for(h=0;h<n.length;h++){var v=n[h];if(k!==k&&v.key!==v.key||k===v.key)return{id:m,list:n,index:h,entry:v}}return{id:m,
list:n,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=q(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(q([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var m=k.entries(),n=m.next();if(n.done||n.value[0]!=h||n.value[1]!="s")return!1;n=m.next();return n.done||n.value[0].x!=
4||n.value[1]!="t"||!m.next().done?!1:!0}catch(v){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var m=d(this,h);m.list||(m.list=this[0][m.id]=[]);m.entry?m.entry.value=k:(m.entry={next:this[1],previous:this[1].previous,head:this[1],key:h,value:k},m.list.push(m.entry),this[1].previous.next=m.entry,this[1].previous=m.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],
h.entry.previous.next=h.entry.next,h.entry.next.previous=h.entry.previous,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].previous=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,
function(h){return h.value})};e.prototype.forEach=function(h,k){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,h.call(k,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
l("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});l("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)u(b,d)&&c.push([d,b[d]]);return c}});
l("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});l("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});l("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});l("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});l("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
l("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});l("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
l("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});
function za(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}l("Array.prototype.entries",function(a){return a?a:function(){return za(this,function(b,c){return[b,c]})}});l("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});
l("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});l("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Aa=this||self;function Ba(a,b){a:{var c=["CLOSURE_FLAGS"];for(var d=Aa,e=0;e<c.length;e++)if(d=d[c[e]],d==null){c=null;break a}c=d}a=c&&c[a];return a!=null?a:b}function Ca(a){return a};var Da=Ba(610401301,!1),Ea=Ba(748402147,!0);function Fa(){return typeof BigInt==="function"};function Ga(a){a.ca=!0;return a};var Ha=Ga(function(a){return typeof a==="number"}),Ia=Ga(function(a){return typeof a==="string"}),Ja=Ga(function(a){return typeof a==="boolean"});var Ka=typeof Aa.BigInt==="function"&&typeof Aa.BigInt(0)==="bigint";function La(a){var b=a;if(Ia(b)){if(!/^\s*(?:-?[1-9]\d*|0)?\s*$/.test(b))throw Error(String(b));}else if(Ha(b)&&!Number.isSafeInteger(b))throw Error(String(b));return Ka?BigInt(a):a=Ja(a)?a?"1":"0":Ia(a)?a.trim()||"0":String(a)}var Ra=Ga(function(a){return Ka?a>=Ma&&a<=Na:a[0]==="-"?Oa(a,Pa):Oa(a,Qa)}),Pa=Number.MIN_SAFE_INTEGER.toString(),Ma=Ka?BigInt(Number.MIN_SAFE_INTEGER):void 0,Qa=Number.MAX_SAFE_INTEGER.toString(),Na=Ka?BigInt(Number.MAX_SAFE_INTEGER):void 0;
function Oa(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var Sa=typeof Uint8Array.prototype.slice==="function",w=0,y=0,Ta;function Ua(a){var b=a>>>0;w=b;y=(a-b)/4294967296>>>0}function Va(a){if(a<0){Ua(-a);var b=q(Wa(w,y));a=b.next().value;b=b.next().value;w=a>>>0;y=b>>>0}else Ua(a)}function Xa(a){var b=Ta||(Ta=new DataView(new ArrayBuffer(8)));b.setFloat32(0,+a,!0);y=0;w=b.getUint32(0,!0)}function Ya(a){var b=Ta||(Ta=new DataView(new ArrayBuffer(8)));b.setFloat64(0,+a,!0);w=b.getUint32(0,!0);y=b.getUint32(4,!0)}
function Za(a,b){var c=b*4294967296+(a>>>0);return Number.isSafeInteger(c)?c:$a(a,b)}function ab(a,b){return La(Fa()?BigInt.asUintN(64,(BigInt(b>>>0)<<BigInt(32))+BigInt(a>>>0)):$a(a,b))}function bb(a,b){return Fa()?La(BigInt.asIntN(64,(BigInt.asUintN(32,BigInt(b))<<BigInt(32))+BigInt.asUintN(32,BigInt(a)))):La(cb(a,b))}
function $a(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else Fa()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+db(c)+db(a));return c}function db(a){a=String(a);return"0000000".slice(a.length)+a}
function cb(a,b){b&2147483648?Fa()?a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0)):(b=q(Wa(a,b)),a=b.next().value,b=b.next().value,a="-"+$a(a,b)):a=$a(a,b);return a}
function eb(a){if(a.length<16)Va(Number(a));else if(Fa())a=BigInt(a),w=Number(a&BigInt(4294967295))>>>0,y=Number(a>>BigInt(32)&BigInt(4294967295));else{var b=+(a[0]==="-");y=w=0;for(var c=a.length,d=b,e=(c-b)%6+b;e<=c;d=e,e+=6)d=Number(a.slice(d,e)),y*=1E6,w=w*1E6+d,w>=4294967296&&(y+=Math.trunc(w/4294967296),y>>>=0,w>>>=0);b&&(b=q(Wa(w,y)),a=b.next().value,b=b.next().value,w=a,y=b)}}function Wa(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]};function fb(a,b){this.h=a>>>0;this.g=b>>>0}function hb(a){return a.h===0?new fb(0,1+~a.g):new fb(~a.h+1,~a.g)}function ib(a){if(!a)return jb||(jb=new fb(0,0));if(!/^\d+$/.test(a))return null;eb(a);return new fb(w,y)}function kb(a){return new fb(a&4294967295,Math.floor(a/4294967296))}var jb;function lb(a,b){this.h=a>>>0;this.g=b>>>0}function mb(a){if(!a)return nb||(nb=new lb(0,0));if(!/^-?\d+$/.test(a))return null;eb(a);return new lb(w,y)}
function ob(a){return new lb(a&4294967295,Math.floor(a/4294967296))}var nb,pb,qb,rb,sb,tb,ub,vb;function wb(a,b,c){if(typeof BigInt64Array!=="undefined")return ub||(ub=new BigInt64Array(1),vb=new Uint32Array(ub.buffer),ub[0]=BigInt(1),tb=vb[0]===1),ub[0]=a,a=tb?0:1,new b(vb[a],vb[1-a]);sb||(pb=BigInt(Number.MIN_SAFE_INTEGER),qb=BigInt(Number.MAX_SAFE_INTEGER),rb=BigInt(4294967295),sb=BigInt(32));if(a>=pb&&a<=qb)return c(Number(a));a=BigInt.asUintN(64,a);return new b(Number(a&rb),Number(a>>sb))};function xb(){throw Error("Invalid UTF8");}function yb(a,b){b=String.fromCharCode.apply(null,b);return a==null?b:a+b}var zb=void 0,Ab,Bb=typeof TextDecoder!=="undefined",Cb,Db=typeof String.prototype.isWellFormed==="function",Eb=typeof TextEncoder!=="undefined";
function Fb(a){var b=!1;b=b===void 0?!1:b;if(Eb){if(b&&(Db?!a.isWellFormed():/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(a)))throw Error("Found an unpaired surrogate");a=(Cb||(Cb=new TextEncoder)).encode(a)}else{for(var c=0,d=new Uint8Array(3*a.length),e=0;e<a.length;e++){var f=a.charCodeAt(e);if(f<128)d[c++]=f;else{if(f<2048)d[c++]=f>>6|192;else{if(f>=55296&&f<=57343){if(f<=56319&&e<a.length){var g=a.charCodeAt(++e);if(g>=56320&&g<=57343){f=(f-55296)*1024+g-56320+
65536;d[c++]=f>>18|240;d[c++]=f>>12&63|128;d[c++]=f>>6&63|128;d[c++]=f&63|128;continue}else e--}if(b)throw Error("Found an unpaired surrogate");f=65533}d[c++]=f>>12|224;d[c++]=f>>6&63|128}d[c++]=f&63|128}}a=c===d.length?d:d.subarray(0,c)}return a};function Gb(a){Aa.setTimeout(function(){throw a;},0)};function Hb(){var a=Aa.navigator;return a&&(a=a.userAgent)?a:""}var Ib,Jb=Aa.navigator;Ib=Jb?Jb.userAgentData||null:null;var Kb={},Lb=null;function Mb(a){var b=a.length,c=b*3/4;c%3?c=Math.floor(c):"=.".indexOf(a[b-1])!=-1&&(c="=.".indexOf(a[b-2])!=-1?c-2:c-1);var d=new Uint8Array(c),e=0;Nb(a,function(f){d[e++]=f});return e!==c?d.subarray(0,e):d}
function Nb(a,b){function c(k){for(;d<a.length;){var m=a.charAt(d++),n=Lb[m];if(n!=null)return n;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return k}Ob();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(h===64&&e===-1)break;b(e<<2|f>>4);g!=64&&(b(f<<4&240|g>>2),h!=64&&b(g<<6&192|h))}}
function Ob(){if(!Lb){Lb={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;c<5;c++){var d=a.concat(b[c].split(""));Kb[c]=d;for(var e=0;e<d.length;e++){var f=d[e];Lb[f]===void 0&&(Lb[f]=e)}}}};var Pb=typeof Uint8Array!=="undefined",Tb=!(Da&&Ib&&Ib.brands.length>0?0:Hb().indexOf("Trident")!=-1||Hb().indexOf("MSIE")!=-1)&&typeof btoa==="function",Ub=/[-_.]/g,Vb={"-":"+",_:"/",".":"="};function Wb(a){return Vb[a]||""}function Xb(a){if(!Tb)return Mb(a);a=Ub.test(a)?a.replace(Ub,Wb):a;a=atob(a);for(var b=new Uint8Array(a.length),c=0;c<a.length;c++)b[c]=a.charCodeAt(c);return b}var Yb={};function Zb(a,b){$b(b);this.g=a;if(a!=null&&a.length===0)throw Error("ByteString should be constructed with non-empty values");}function ac(){return bc||(bc=new Zb(null,Yb))}function cc(a){$b(Yb);var b=a.g;b=b==null||Pb&&b!=null&&b instanceof Uint8Array?b:typeof b==="string"?Xb(b):null;return b==null?b:a.g=b}var bc;function $b(a){if(a!==Yb)throw Error("illegal external caller");};function dc(a,b,c){this.buffer=a;if(c&&!b)throw Error();this.g=b}
function ec(a,b){if(typeof a==="string")return new dc(Xb(a),b);if(Array.isArray(a))return new dc(new Uint8Array(a),b);if(a.constructor===Uint8Array)return new dc(a,!1);if(a.constructor===ArrayBuffer)return a=new Uint8Array(a),new dc(a,!1);if(a.constructor===Zb)return b=cc(a)||new Uint8Array(0),new dc(b,!0,a);if(a instanceof Uint8Array)return a=a.constructor===Uint8Array?a:new Uint8Array(a.buffer,a.byteOffset,a.byteLength),new dc(a,!1);throw Error();};function fc(a,b,c,d){this.h=null;this.m=!1;this.g=this.i=this.j=0;this.init(a,b,c,d)}fc.prototype.init=function(a,b,c,d){var e=d===void 0?{}:d;d=e.P===void 0?!1:e.P;e=e.S===void 0?!1:e.S;this.P=d;this.S=e;a&&(a=ec(a,this.S),this.h=a.buffer,this.m=a.g,this.j=b||0,this.i=c!==void 0?this.j+c:this.h.length,this.g=this.j)};fc.prototype.clear=function(){this.h=null;this.m=!1;this.g=this.i=this.j=0;this.P=!1};
function hc(a,b){var c=0,d=0,e=0,f=a.h,g=a.g;do{var h=f[g++];c|=(h&127)<<e;e+=7}while(e<32&&h&128);if(e>32)for(d|=(h&127)>>4,e=3;e<32&&h&128;e+=7)h=f[g++],d|=(h&127)<<e;ic(a,g);if(!(h&128))return b(c>>>0,d>>>0);throw Error();}function ic(a,b){a.g=b;if(b>a.i)throw Error();}
function jc(a){var b=a.h,c=a.g,d=b[c++],e=d&127;if(d&128&&(d=b[c++],e|=(d&127)<<7,d&128&&(d=b[c++],e|=(d&127)<<14,d&128&&(d=b[c++],e|=(d&127)<<21,d&128&&(d=b[c++],e|=d<<28,d&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128)))))throw Error();ic(a,c);return e}function kc(a){return jc(a)>>>0}function lc(a){a=kc(a);return a>>>1^-(a&1)}function mc(a){return hc(a,bb)}function nc(a){var b=a.h,c=a.g,d=b[c],e=b[c+1],f=b[c+2];b=b[c+3];ic(a,a.g+4);return(d<<0|e<<8|f<<16|b<<24)>>>0}
function oc(a){var b=nc(a);a=(b>>31)*2+1;var c=b>>>23&255;b&=8388607;return c==255?b?NaN:a*Infinity:c==0?a*1.401298464324817E-45*b:a*Math.pow(2,c-150)*(b+8388608)}function pc(a){var b=nc(a),c=nc(a);a=(c>>31)*2+1;var d=c>>>20&2047;b=4294967296*(c&1048575)+b;return d==2047?b?NaN:a*Infinity:d==0?a*4.9E-324*b:a*Math.pow(2,d-1075)*(b+4503599627370496)}function qc(a){for(var b=0,c=a.g,d=c+10,e=a.h;c<d;){var f=e[c++];b|=f;if((f&128)===0)return ic(a,c),!!(b&127)}throw Error();}
function rc(a){return jc(a)}function sc(a,b){if(b<0)throw Error();var c=a.g;b=c+b;if(b>a.i)throw Error();a.g=b;return c}function tc(a,b){if(b==0)return ac();var c=sc(a,b);a.P&&a.m?c=a.h.subarray(c,c+b):(a=a.h,b=c+b,c=c===b?new Uint8Array(0):Sa?a.slice(c,b):new Uint8Array(a.subarray(c,b)));return c.length==0?ac():new Zb(c,Yb)}var uc=[],vc=void 0;function wc(){this.g=[]}wc.prototype.length=function(){return this.g.length};wc.prototype.end=function(){var a=this.g;this.g=[];return a};function xc(a,b,c){for(;c>0||b>127;)a.g.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.g.push(b)}function yc(a,b){for(;b>127;)a.g.push(b&127|128),b>>>=7;a.g.push(b)}function zc(a,b){if(b>=0)yc(a,b);else{for(var c=0;c<9;c++)a.g.push(b&127|128),b>>=7;a.g.push(1)}}function z(a,b){a.g.push(b>>>0&255);a.g.push(b>>>8&255);a.g.push(b>>>16&255);a.g.push(b>>>24&255)};var Ac=0;function Bc(a,b,c,d){if(uc.length){var e=uc.pop();e.init(a,b,c,d);a=e}else a=new fc(a,b,c,d);this.g=a;this.j=this.g.g;this.h=this.i=-1;this.setOptions(d)}Bc.prototype.setOptions=function(a){a=a===void 0?{}:a;this.U=a.U===void 0?!1:a.U};function Cc(a,b,c,d){if(Dc.length){var e=Dc.pop();e.setOptions(d);e.g.init(a,b,c,d);return e}return new Bc(a,b,c,d)}function Ec(a){a.g.clear();a.i=-1;a.h=-1;Dc.length<100&&Dc.push(a)}
function Fc(a){var b=a.g;if(b.g==b.i)return!1;a.j=a.g.g;var c=kc(a.g);b=c>>>3;c&=7;if(!(c>=0&&c<=5))throw Error();if(b<1)throw Error();a.i=b;a.h=c;return!0}function Gc(){if(Ac>=100)throw new SyntaxError;Ac++}
function Hc(a){try{switch(a.h){case 0:a.h!=0?Hc(a):qc(a.g);break;case 1:var b=a.g;ic(b,b.g+8);break;case 2:if(a.h!=2)Hc(a);else{var c=kc(a.g),d=a.g;ic(d,d.g+c)}break;case 5:var e=a.g;ic(e,e.g+4);break;case 3:Gc();var f=a.i;try{do{if(!Fc(a))throw Error();if(a.h==4){if(a.i!=f)throw Error();break}Hc(a)}while(1)}catch(g){if(g instanceof RangeError)throw new SyntaxError;throw g;}finally{Ac>0&&Ac--}break;default:throw Error();}}catch(g){if(g instanceof RangeError)throw new SyntaxError;throw g;}}
function Ic(a,b,c){var d=a.g.i,e=kc(a.g);e=a.g.g+e;var f=e-d;f<=0&&(a.g.i=e,c(b,a,void 0,void 0,void 0),f=e-a.g.g);if(f)throw Error();a.g.g=e;a.g.i=d;return b}
function Jc(a){var b=kc(a.g);a=a.g;var c=sc(a,b);a=a.h;if(Bb){var d=a,e;(e=Ab)||(e=Ab=new TextDecoder("utf-8",{fatal:!0}));b=c+b;d=c===0&&b===d.length?d:d.subarray(c,b);try{var f=e.decode(d)}catch(m){if(zb===void 0){try{e.decode(new Uint8Array([128]))}catch(n){}try{e.decode(new Uint8Array([97])),zb=!0}catch(n){zb=!1}}!zb&&(Ab=void 0);throw m;}}else{f=c;b=f+b;c=[];for(var g=null,h,k;f<b;)h=a[f++],h<128?c.push(h):h<224?f>=b?xb():(k=a[f++],h<194||(k&192)!==128?(f--,xb()):c.push((h&31)<<6|k&63)):h<240?
f>=b-1?xb():(k=a[f++],(k&192)!==128||h===224&&k<160||h===237&&k>=160||((e=a[f++])&192)!==128?(f--,xb()):c.push((h&15)<<12|(k&63)<<6|e&63)):h<=244?f>=b-2?xb():(k=a[f++],(k&192)!==128||(h<<28)+(k-144)>>30!==0||((e=a[f++])&192)!==128||((d=a[f++])&192)!==128?(f--,xb()):(h=(h&7)<<18|(k&63)<<12|(e&63)<<6|d&63,h-=65536,c.push((h>>10&1023)+55296,(h&1023)+56320))):xb(),c.length>=8192&&(g=yb(g,c),c.length=0);f=yb(g,c)}return f}function Kc(a){var b=kc(a.g);return tc(a.g,b)}
function Lc(a,b,c){var d=kc(a.g);for(d=a.g.g+d;a.g.g<d;)c.push(b(a.g))}var Dc=[];function Mc(){this.i=[];this.h=0;this.g=new wc}function Nc(a,b){b.length!==0&&(a.i.push(b),a.h+=b.length)}function Oc(a,b){B(a,b,2);b=a.g.end();Nc(a,b);b.push(a.h);return b}function Pc(a,b){var c=b.pop();for(c=a.h+a.g.length()-c;c>127;)b.push(c&127|128),c>>>=7,a.h++;b.push(c);a.h++}function B(a,b,c){yc(a.g,b*8+c)}function Qc(a,b,c){c!=null&&(c=parseInt(c,10),B(a,b,0),zc(a.g,c))}function Rc(a,b,c){B(a,b,2);yc(a.g,c.length);Nc(a,a.g.end());Nc(a,c)}
function Sc(a,b,c,d){c!=null&&(b=Oc(a,b),d(c,a),Pc(a,b))}function Tc(a){switch(typeof a){case "string":a.length&&a[0]==="-"?ib(a.substring(1)):ib(a)}};var Uc=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Vc(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Wc=Vc("jas",void 0,!0),Xc=Vc(void 0,"1oa"),Yc=Vc(void 0,Symbol()),Zc=Vc(void 0,"0ubs"),$c=Vc(void 0,"0ubsb"),ad=Vc(void 0,"0actk"),bd=Vc("m_m","da",!0);var cd={ba:{value:0,configurable:!0,writable:!0,enumerable:!1}},dd=Object.defineProperties,D=Uc?Wc:"ba",ed,fd=[];E(fd,7);ed=Object.freeze(fd);function gd(a,b){Uc||D in a||dd(a,cd);a[D]|=b}function E(a,b){Uc||D in a||dd(a,cd);a[D]=b}function hd(a){gd(a,8192);return a};var id={};function jd(a,b){return b===void 0?a.g!==kd&&!!(2&(a.l[D]|0)):!!(2&b)&&a.g!==kd}var kd={};function pd(a,b,c){var d=b&128?0:-1,e=a.length,f;if(f=!!e)f=a[e-1],f=f!=null&&typeof f==="object"&&f.constructor===Object;var g=e+(f?-1:0);for(b=b&128?1:0;b<g;b++)c(b-d,a[b]);if(f){a=a[e-1];for(var h in a)!isNaN(h)&&c(+h,a[h])}}var qd={};function rd(a){return a&128?qd:void 0};function sd(a){return a};var td=void 0;function ud(a,b){if(a!=null){var c;var d=(c=td)!=null?c:td={};c=d[a]||0;c>=b||(d[a]=c+1,a=Error(),a.__closure__error__context__984382||(a.__closure__error__context__984382={}),a.__closure__error__context__984382.severity="incident",Gb(a))}};function vd(a){return Array.prototype.slice.call(a)};var wd=typeof BigInt==="function"?BigInt.asIntN:void 0,xd=typeof BigInt==="function"?BigInt.asUintN:void 0,yd=Number.isSafeInteger,zd=Number.isFinite,Ad=Math.trunc;function Bd(a){if(a!=null&&typeof a!=="number")throw Error("Value of float/double field must be a number, found "+typeof a+": "+a);return a}function Cd(a){if(a==null||typeof a==="number")return a;if(a==="NaN"||a==="Infinity"||a==="-Infinity")return Number(a)}
function Dd(a){if(a==null||typeof a==="boolean")return a;if(typeof a==="number")return!!a}var Ed=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;function Fd(a){switch(typeof a){case "bigint":return!0;case "number":return zd(a);case "string":return Ed.test(a);default:return!1}}function Gd(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return zd(a)?a|0:void 0}
function Hd(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return zd(a)?a>>>0:void 0}
function Id(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(wd(64,a));if(Fd(a)){if(b==="string")return b=Ad(Number(a)),yd(b)?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),b=a.length,(a[0]==="-"?b<20||b===20&&a<="-9223372036854775808":b<19||b===19&&a<="9223372036854775807")||(eb(a),a=cb(w,y))),a;if(b==="number"){a=Ad(a);if(!yd(a)){Va(a);b=w;var c=y;if(a=c&2147483648)b=~b+1>>>0,c=~c>>>0,b==0&&(c=c+1>>>0);b=Za(b,c);a=typeof b==="number"?a?-b:b:a?"-"+b:b}return a}}}
function Jd(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(xd(64,a));if(Fd(a)){if(b==="string")return b=Ad(Number(a)),yd(b)&&b>=0?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),a[0]==="-"?b=!1:(b=a.length,b=b<20?!0:b===20&&a<="18446744073709551615"),b||(eb(a),a=$a(w,y))),a;if(b==="number")return a=Ad(a),a>=0&&yd(a)||(Va(a),a=Za(w,y)),a}}function Kd(a){if(a==null||typeof a=="string"||a instanceof Zb)return a}
function Ld(a){if(a!=null&&typeof a!=="string")throw Error();return a}function Md(a){return a==null||typeof a==="string"?a:void 0};function Nd(a){var b=Ca(Yc);return b?a[b]:void 0}function Od(){}function Pd(a,b){for(var c in a)!isNaN(c)&&b(a,+c,a[c])}function Qd(a){var b=new Od;Pd(a,function(c,d,e){b[d]=vd(e)});b.g=a.g;return b}function Rd(a,b){b<100||ud(Zc,1)};function Sd(a,b,c,d){var e=d!==void 0;d=!!d;var f=Ca(Yc),g;!e&&Uc&&f&&(g=a[f])&&Pd(g,Rd);f=[];var h=a.length;g=4294967295;var k=!1,m=!!(b&64),n=m?b&128?0:-1:void 0;if(!(b&1)){var v=h&&a[h-1];v!=null&&typeof v==="object"&&v.constructor===Object?(h--,g=h):v=void 0;if(m&&!(b&128)&&!e){k=!0;var x;g=((x=Td)!=null?x:sd)(g-n,n,a,v,void 0)+n}}b=void 0;for(x=0;x<h;x++){var A=a[x];if(A!=null&&(A=c(A,d))!=null)if(m&&x>=g){var F=x-n,C=void 0;((C=b)!=null?C:b={})[F]=A}else f[x]=A}if(v)for(var M in v)h=v[M],h!=
null&&(h=c(h,d))!=null&&(x=+M,A=void 0,m&&!Number.isNaN(x)&&(A=x+n)<g?f[A]=h:(x=void 0,((x=b)!=null?x:b={})[M]=h));b&&(k?f.push(b):f[g]=b);e&&Ca(Yc)&&(a=Nd(a))&&a instanceof Od&&(f[Yc]=Qd(a));return f}
function Ud(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return Ra(a)?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[D]|0;return a.length===0&&b&1?void 0:Sd(a,b,Ud)}if(a!=null&&a[bd]===id)return Vd(a);if(a instanceof Zb){b=a.g;if(b==null)a="";else if(typeof b==="string")a=b;else{if(Tb){for(var c="",d=0,e=b.length-10240;d<e;)c+=String.fromCharCode.apply(null,b.subarray(d,d+=10240));c+=String.fromCharCode.apply(null,d?b.subarray(d):
b);b=btoa(c)}else{c===void 0&&(c=0);Ob();c=Kb[c];d=Array(Math.floor(b.length/3));e=c[64]||"";for(var f=0,g=0;f<b.length-2;f+=3){var h=b[f],k=b[f+1],m=b[f+2],n=c[h>>2];h=c[(h&3)<<4|k>>4];k=c[(k&15)<<2|m>>6];m=c[m&63];d[g++]=n+h+k+m}n=0;m=e;switch(b.length-f){case 2:n=b[f+1],m=c[(n&15)<<2]||e;case 1:b=b[f],d[g]=c[b>>2]+c[(b&3)<<4|n>>4]+m+e}b=d.join("")}a=a.g=b}return a}return}return a}var Td;function Vd(a){a=a.l;return Sd(a,a[D]|0,Ud)};var Wd,Xd;function Yd(a){switch(typeof a){case "boolean":return Wd||(Wd=[0,void 0,!0]);case "number":return a>0?void 0:a===0?Xd||(Xd=[0,void 0]):[-a,void 0];case "string":return[0,a];case "object":return a}}function Zd(a,b){return G(a,b[0],b[1])}
function G(a,b,c,d){d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("narr");e=a[D]|0;if(Ea&&1&e)throw Error("rfarr");2048&e&&!(2&e)&&$d();if(e&256)throw Error("farr");if(e&64)return(e|d)!==e&&E(a,e|d),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var f=c.length;if(f){var g=f-1,h=c[g];if(h!=null&&typeof h==="object"&&h.constructor===Object){b=e&128?0:-1;g-=b;if(g>=1024)throw Error("pvtlmt");for(var k in h)f=
+k,f<g&&(c[f+b]=h[k],delete h[k]);e=e&-16760833|(g&1023)<<14;break a}}if(b){k=Math.max(b,f-(e&128?0:-1));if(k>1024)throw Error("spvt");e=e&-16760833|(k&1023)<<14}}}E(a,e|64|d);return a}function $d(){if(Ea)throw Error("carr");ud(ad,5)};function ae(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[D]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=be(a,c,!1,b&&!(c&16)):(gd(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[bd]===id)return b=a.l,c=b[D]|0,jd(a,c)?a:ce(a,b,c)?de(a,b):be(b,c);if(a instanceof Zb)return a}function de(a,b,c){a=new a.constructor(b);c&&(a.g=kd);a.h=kd;return a}function be(a,b,c,d){d!=null||(d=!!(34&b));a=Sd(a,b,ae,d);d=32;c&&(d|=2);b=b&16769217|d;E(a,b);return a}
function ee(a){if(a.g!==kd)return!1;var b=a.l;b=be(b,b[D]|0);gd(b,2048);a.l=b;a.g=void 0;a.h=void 0;return!0}function fe(a){if(!ee(a)&&jd(a,a.l[D]|0))throw Error();}function ge(a,b){b===void 0&&(b=a[D]|0);b&32&&!(b&4096)&&E(a,b|4096)}function ce(a,b,c){return c&2?!0:c&32&&!(c&4096)?(E(b,c|2),a.g=kd,!0):!1};function he(a,b,c){a=ie(a.l,b,void 0,c);if(a!==null)return a}function ie(a,b,c,d){if(b===-1)return null;var e=b+(c?0:-1),f=a.length-1;if(!(f<1+(c?0:-1))){if(e>=f){var g=a[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){c=g[b];var h=!0}else if(e===f)c=g;else return}else c=a[e];if(d&&c!=null){d=d(c);if(d==null)return d;if(!Object.is(d,c))return h?g[b]=d:a[e]=d,d}return c}}function je(a,b,c){fe(a);var d=a.l;H(d,d[D]|0,b,c);return a}
function H(a,b,c,d,e){var f=c+(e?0:-1),g=a.length-1;if(g>=1+(e?0:-1)&&f>=g){var h=a[g];if(h!=null&&typeof h==="object"&&h.constructor===Object)return h[c]=d,b}if(f<=g)return a[f]=d,b;if(d!==void 0){var k;g=((k=b)!=null?k:b=a[D]|0)>>14&1023||536870912;c>=g?d!=null&&(f={},a[g+(e?0:-1)]=(f[c]=d,f)):a[f]=d}return b}function ke(a,b){return le(a,a[D]|0,b)}function me(a){return!!(2&a)&&!!(4&a)||!!(256&a)}
function ne(a){return a==null?a:typeof a==="string"?a?new Zb(a,Yb):ac():a.constructor===Zb?a:Pb&&a!=null&&a instanceof Uint8Array?a.length?new Zb(new Uint8Array(a),Yb):ac():void 0}function le(a,b,c){if(b&2)throw Error();var d=rd(b);var e=ie(a,c,d);e=Array.isArray(e)?e:ed;var f=e===ed?7:e[D]|0;var g=f;2&b&&(g|=2);g|=1;if(2&g||me(g)||16&g)g===f||me(g)||E(e,g),e=vd(e),f=0,g=oe(g,b),H(a,b,c,e,d);g&=-13;g!==f&&E(e,g);return e}
function pe(a,b,c,d){fe(a);var e=a.l,f=e[D]|0;if(d==null){var g=qe(e);if(re(g,e,f,c)===b)g.set(c,0);else return a}else f=se(e,f,c,b);H(e,f,b,d);return a}function te(a,b,c,d){var e=a[D]|0,f=rd(e);e=se(a,e,c,b,f);H(a,e,b,d,f)}function qe(a){if(Uc){var b;return(b=a[Xc])!=null?b:a[Xc]=new Map}if(Xc in a)return a[Xc];b=new Map;Object.defineProperty(a,Xc,{value:b});return b}function se(a,b,c,d,e){var f=qe(a),g=re(f,a,b,c,e);g!==d&&(g&&(b=H(a,b,g,void 0,e)),f.set(c,d));return b}
function re(a,b,c,d,e){var f=a.get(d);if(f!=null)return f;for(var g=f=0;g<d.length;g++){var h=d[g];ie(b,h,e)!=null&&(f!==0&&(c=H(b,c,f,void 0,e)),f=h)}a.set(d,f);return f}function ue(a,b,c){var d=a[D]|0,e=rd(d),f=ie(a,c,e);if(f!=null&&f[bd]===id){if(!jd(f))return ee(f),f.l;var g=f.l}else Array.isArray(f)&&(g=f);if(g){var h=g[D]|0;h&2&&(g=be(g,h))}g=Zd(g,b);g!==f&&H(a,d,c,g,e);return g}
function ve(a,b){var c=we,d=!1,e=ie(a,4,void 0,function(f){if(f!=null&&f[bd]===id)var g=f;else if(Array.isArray(f)){g=f[D]|0;var h=g|b&32;h|=b&2;h!==g&&E(f,h);g=new c(f)}else g=void 0;d=g!==f&&g!=null;return g});if(e!=null)return d&&!jd(e)&&ge(a,b),e}function xe(a){var b=a.l,c=b[D]|0,d=ve(b,c);if(d==null)return d;c=b[D]|0;if(!jd(a,c)){var e=d;var f=e.l,g=f[D]|0;e=jd(e,g)?ce(e,f,g)?de(e,f,!0):new e.constructor(be(f,g,!1)):e;e!==d&&(ee(a)&&(b=a.l,c=b[D]|0),d=e,c=H(b,c,4,d),ge(b,c))}return d}
function ye(a){a==null&&(a=void 0);return a}function ze(a,b,c){c=ye(c);je(a,b,c);c&&!jd(c)&&ge(a.l);return a}function Ae(a,b){fe(a);var c=a.l,d=c[D]|0;if(b==null)return H(c,d,1),a;for(var e=b===ed?7:b[D]|0,f=e,g=me(e),h=g||Object.isFrozen(b),k=!0,m=!0,n=0;n<b.length;n++){var v=b[n];g||(v=jd(v),k&&(k=!v),m&&(m=v))}g||(e=k?13:5,e=m?e&-4097:e|4096);h&&e===f||(b=vd(b),f=0,e=oe(e,d));e!==f&&E(b,e);d=H(c,d,1,b);2&e||!(4096&e||16&e)||ge(c,d);return a}function oe(a,b){return a=(2&b?a|2:a&-3)&-273};function I(a,b,c){this.l=G(a,b,c,2048)}I.prototype.toJSON=function(){var a=Vd(this);return a};I.prototype[bd]=id;I.prototype.toString=function(){return this.l.toString()};function J(){function a(){throw Error();}Object.setPrototypeOf(a,a.prototype);return a}var Be=J(),Ce=J(),De=J(),Ee=J(),Fe=J(),Ge=J(),He=J(),Ie=J(),Je=J(),Ke=J();function Le(a,b,c){this.g=a;this.h=b;a=Ca(Be);this.i=!!a&&c===a||!1}function Me(a,b){var c=c===void 0?Be:c;return new Le(a,b,c)}function Ne(a,b,c,d,e){Sc(a,c,Oe(b,d),e)}var Pe=Me(function(a,b,c,d,e){if(a.h!==2)return!1;Ic(a,ue(b,d,c),e);return!0},Ne),Qe=Me(function(a,b,c,d,e){if(a.h!==2)return!1;Ic(a,ue(b,d,c),e);return!0},Ne),Re=Symbol(),Se=Symbol(),Te=Symbol(),Ue=Symbol(),Ve=Symbol(),We,Xe;
function Ye(a,b,c,d){var e=d[a];if(e)return e;e={};e.aa=d;e.O=Yd(d[0]);var f=d[1],g=1;f&&f.constructor===Object&&(e.V=f,f=d[++g],typeof f==="function"&&(e.Y=!0,We!=null||(We=f),Xe!=null||(Xe=d[g+1]),f=d[g+=2]));for(var h={};f&&Array.isArray(f)&&f.length&&typeof f[0]==="number"&&f[0]>0;){for(var k=0;k<f.length;k++)h[f[k]]=f;f=d[++g]}for(k=1;f!==void 0;){typeof f==="number"&&(k+=f,f=d[++g]);var m=void 0;if(f instanceof Le)var n=f;else n=Pe,g--;f=void 0;if((f=n)==null?0:f.i){f=d[++g];m=d;var v=g;typeof f===
"function"&&(f=f(),m[v]=f);m=f}f=d[++g];v=k+1;typeof f==="number"&&f<0&&(v-=f,f=d[++g]);for(;k<v;k++){var x=h[k];m?c(e,k,n,m,x):b(e,k,n,x)}}return d[a]=e}function Ze(a){return Array.isArray(a)?a[0]instanceof Le?a:[Qe,a]:[a,void 0]}function Oe(a,b){if(a instanceof I)return a.l;if(Array.isArray(a))return Zd(a,b)};function $e(a,b,c,d){var e=c.g;a[b]=d?function(f,g,h){return e(f,g,h,d)}:e}function af(a,b,c,d,e){var f=c.g,g,h;a[b]=function(k,m,n){return f(k,m,n,h||(h=Ye(Se,$e,af,d).O),g||(g=bf(d)),e)}}
function bf(a){var b=a[Te];if(b!=null)return b;var c=Ye(Se,$e,af,a);b=c.Y?function(d,e){return We(d,e,c)}:function(d,e){a:{Gc();try{for(;Fc(e)&&e.h!=4;){var f=e.i,g=c[f];if(g==null){var h=c.V;if(h){var k=h[f];if(k){var m=cf(k);m!=null&&(g=c[f]=m)}}}if(g==null||!g(e,d,f)){var n=e,v=n.j;Hc(n);if(n.U)var x=void 0;else{var A=n.g.g-v;n.g.g=v;x=tc(n.g,A)}var F=n=void 0,C=void 0,M=d,Qb=f,wa=x;wa&&((n=(F=(C=M[Yc])!=null?C:M[Yc]=new Od)[Qb])!=null?n:F[Qb]=[]).push(wa)}}var Rb=Nd(d);Rb&&(Rb.g=c.aa[Ve]);var gb=
!0;break a}catch(Sb){if(Sb instanceof RangeError)throw new SyntaxError;throw Sb;}finally{Ac>0&&Ac--}gb=void 0}return gb};a[Te]=b;a[Ve]=df.bind(a);return b}
function df(a,b,c,d){var e=this[Se],f=this[Te],g=Zd(void 0,e.O),h=Nd(a);if(h){var k=!1,m=e.V;if(m){e=function(F,C,M){if(M.length!==0)if(m[C])for(F=q(M),C=F.next();!C.done;C=F.next()){C=Cc(C.value);try{k=!0,f(g,C)}finally{Ec(C)}}else d==null||d(a,C,M)};if(b==null)Pd(h,e);else if(h!=null){var n=h[b];n&&e(h,b,n)}if(k){var v=a[D]|0;if(v&2&&v&2048&&(c==null||!c.fa))throw Error();var x=rd(v),A=function(F,C){if(ie(a,F,x)!=null)switch(c==null?void 0:c.ea){case 1:return;default:throw Error();}C!=null&&(v=
H(a,v,F,C,x));delete h[F]};b==null?pd(g,g[D]|0,function(F,C){A(F,C)}):A(b,ie(g,b,x))}}}}function cf(a){a=Ze(a);var b=a[0].g;if(a=a[1]){var c=bf(a),d=Ye(Se,$e,af,a).O;return function(e,f,g){return b(e,f,g,d,c)}}return b};function ef(a,b,c){a[b]=c.h}function ff(a,b,c,d){var e,f,g=c.h;a[b]=function(h,k,m){return g(h,k,m,f||(f=Ye(Re,ef,ff,d).O),e||(e=gf(d)))}}function gf(a){var b=a[Ue];if(!b){var c=Ye(Re,ef,ff,a);b=function(d,e){return hf(d,e,c)};a[Ue]=b}return b}function hf(a,b,c){pd(a,a[D]|0,function(d,e){if(e!=null){var f=jf(c,d);f?f(b,e,d):d<500||ud($c,3)}});(a=Nd(a))&&Pd(a,function(d,e,f){Nc(b,b.g.end());for(d=0;d<f.length;d++)Nc(b,cc(f[d])||new Uint8Array(0))})}
function jf(a,b){var c=a[b];if(c)return c;if(c=a.V)if(c=c[b]){c=Ze(c);var d=c[0].h;if(c=c[1]){var e=gf(c),f=Ye(Re,ef,ff,c).O;c=a.Y?Xe(f,e):function(g,h,k){return d(g,h,k,f,e)}}else c=d;return a[b]=c}};function K(a,b,c){if(Array.isArray(b)){var d=b[D]|0;if(d&4)return b;for(var e=0,f=0;e<b.length;e++){var g=a(b[e]);g!=null&&(b[f++]=g)}f<e&&(b.length=f);a=d|1;c&&(a=(a|4)&-1537);a!==d&&E(b,a);c&&a&2&&Object.freeze(b);return b}}function L(a,b,c){return new Le(a,b,c)}function N(a,b,c){return new Le(a,b,c)}function O(a,b,c){H(a,a[D]|0,b,c,rd(a[D]|0))}
var kf=Me(function(a,b,c,d,e){if(a.h!==2)return!1;a=Ic(a,Zd([void 0,void 0],d),e);a=vd(a);d=b[D]|0;e=rd(d);if(d&2)throw Error();var f=ie(b,c,e);if(Array.isArray(f)){var g=f[D]|0;g&8192||E(f,g|=8192);if(g&2){f=vd(f);for(g=0;g<f.length;g++){var h=f[g]=vd(f[g]);if(Array.isArray(h[1])){var k=h[1];gd(k,34);h[1]=k}}f=hd(f);H(b,d,c,f,e)}f.push(a)}else H(b,d,c,hd([a]),e);return!0},function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++){var g=b[f];Array.isArray(g)&&Sc(a,c,Zd(g,d),e)}hd(b)}});
function lf(a,b,c){b=Cd(b);b!=null&&(B(a,c,1),a=a.g,Ya(b),z(a,w),z(a,y))}function mf(a,b,c){b=Cd(b);b!=null&&(B(a,c,5),a=a.g,Xa(b),z(a,w))}function nf(a,b,c){b=Id(b);if(b!=null){switch(typeof b){case "string":mb(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Va(b);xc(a,w,y);break;case "bigint":c=wb(b,lb,ob);xc(a.g,c.h,c.g);break;default:c=mb(b),xc(a.g,c.h,c.g)}}}
function of(a,b,c){b=Jd(b);if(b!=null){switch(typeof b){case "string":ib(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Va(b);xc(a,w,y);break;case "bigint":c=wb(b,fb,kb);xc(a.g,c.h,c.g);break;default:c=ib(b),xc(a.g,c.h,c.g)}}}function pf(a,b,c){b=Gd(b);b!=null&&b!=null&&(B(a,c,0),zc(a.g,b))}function qf(a,b,c){b=Dd(b);b!=null&&(B(a,c,0),a.g.g.push(b?1:0))}function rf(a,b,c){b=Md(b);b!=null&&Rc(a,c,Fb(b))}function sf(a,b,c,d,e){Sc(a,c,Oe(b,d),e)}function tf(a,b,c){Qc(a,c,Gd(b))}
function uf(a,b,c){if(a.h!==5&&a.h!==2)return!1;b=ke(b,c);a.h==2?Lc(a,oc,b):b.push(oc(a.g));return!0}function vf(a,b,c){if(a.h!==0)return!1;O(b,c,hc(a.g,ab));return!0}function wf(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=ke(b,c);a.h==2?Lc(a,jc,b):b.push(jc(a.g));return!0}function xf(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=ke(b,c);a.h==2?Lc(a,qc,b):b.push(qc(a.g));return!0}
var yf=L(function(a,b,c){if(a.h!==1)return!1;O(b,c,pc(a.g));return!0},lf,Ie),zf=L(function(a,b,c,d){if(a.h!==1)return!1;te(b,c,d,pc(a.g));return!0},lf,Ie),P=L(function(a,b,c){if(a.h!==5)return!1;O(b,c,oc(a.g));return!0},mf,He),Af=N(uf,function(a,b,c){b=K(Cd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,5),e=e.g,Xa(g),z(e,w))}},He),Q=N(uf,function(a,b,c){b=K(Cd,b,!0);if(b!=null&&b.length)for(B(a,c,2),yc(a.g,b.length*4),c=0;c<b.length;c++){var d=a.g;Xa(b[c]);z(d,w)}},
He),Bf=L(function(a,b,c,d){if(a.h!==5)return!1;te(b,c,d,oc(a.g));return!0},mf,He),Cf=L(function(a,b,c){a.h!==0?a=!1:(O(b,c,mc(a.g)),a=!0);return a},nf,Fe),Df=N(function(a,b,c){a.h!==0&&a.h!==2?a=!1:(b=ke(b,c),a.h==2?Lc(a,mc,b):b.push(mc(a.g)),a=!0);return a},function(a,b,c){b=K(Id,b,!1);if(b!=null&&b.length){c=Oc(a,c);for(var d=0;d<b.length;d++){var e=b[d];switch(typeof e){case "number":var f=a.g;Va(e);xc(f,w,y);break;case "bigint":e=wb(e,lb,ob);xc(a.g,e.h,e.g);break;default:e=mb(e),xc(a.g,e.h,e.g)}}Pc(a,
c)}},Fe),Ef=L(function(a,b,c,d){a.h!==0?a=!1:(te(b,c,d,mc(a.g)),a=!0);return a},nf,Fe),Ff=L(function(a,b,c){return vf(a,b,c)},of,Ge),Gf=L(function(a,b,c){return vf(a,b,c)},of,Ge),R=L(function(a,b,c){if(a.h!==0)return!1;O(b,c,jc(a.g));return!0},pf,Ee),Hf=N(wf,function(a,b,c){b=K(Gd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),zc(e.g,g))}},Ee),If=N(wf,function(a,b,c){b=K(Gd,b,!0);if(b!=null&&b.length){c=Oc(a,c);for(var d=0;d<b.length;d++)zc(a.g,b[d]);Pc(a,c)}},
Ee),Jf=L(function(a,b,c,d){if(a.h!==0)return!1;te(b,c,d,jc(a.g));return!0},pf,Ee),S=L(function(a,b,c){if(a.h!==0)return!1;O(b,c,qc(a.g));return!0},qf,Ce),Kf=N(xf,function(a,b,c){b=K(Dd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),e.g.g.push(g?1:0))}},Ce),Lf=N(xf,function(a,b,c){b=K(Dd,b,!0);if(b!=null&&b.length)for(B(a,c,2),yc(a.g,b.length),c=0;c<b.length;c++)a.g.g.push(b[c]?1:0)},Ce),Mf=L(function(a,b,c,d){if(a.h!==0)return!1;te(b,c,d,qc(a.g));return!0},qf,Ce),
T=L(function(a,b,c){if(a.h!==2)return!1;O(b,c,Jc(a));return!0},rf,De),Nf=L(function(a,b,c,d){if(a.h!==2)return!1;te(b,c,d,Jc(a));return!0},rf,De),U=N(function(a,b,c){if(a.h!==2)return!1;a=Jc(a);le(b,b[D]|0,c).push(a);return!0},function(a,b,c){b=K(Md,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&Rc(e,f,Fb(g))}},De),V,Of=void 0;Of=Of===void 0?Be:Of;
V=new Le(function(a,b,c,d,e){if(a.h!==2)return!1;d=Zd(void 0,d);le(b,b[D]|0,c).push(d);Ic(a,d,e);return!0},function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)sf(a,b[f],c,d,e);a=b[D]|0;a&1||E(b,a|1)}},Of);
var W=Me(function(a,b,c,d,e,f){if(a.h!==2)return!1;var g=b[D]|0;se(b,g,f,c,rd(g));b=ue(b,d,c);Ic(a,b,e);return!0},sf),Pf=L(function(a,b,c){if(a.h!==2)return!1;O(b,c,Kc(a));return!0},function(a,b,c){b=Kd(b);b!=null&&Rc(a,c,ec(b,!0).buffer)},Je),X=L(function(a,b,c){if(a.h!==0)return!1;O(b,c,kc(a.g));return!0},function(a,b,c){b=Hd(b);b!=null&&b!=null&&(B(a,c,0),yc(a.g,b))},J()),Y=L(function(a,b,c){if(a.h!==0)return!1;O(b,c,jc(a.g));return!0},tf,Ke),Qf=N(function(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=
ke(b,c);a.h==2?Lc(a,rc,b):b.push(jc(a.g));return!0},function(a,b,c){b=K(Gd,b,!0);if(b!=null)for(var d=0;d<b.length;d++)Qc(a,c,b[d])},Ke),Rf=L(function(a,b,c,d){if(a.h!==0)return!1;te(b,c,d,jc(a.g));return!0},tf,Ke),Sf=N(function(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=ke(b,c);a.h==2?Lc(a,lc,b):b.push(lc(a.g));return!0},function(a,b,c){b=K(Gd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),yc(e.g,(g<<1^g>>31)>>>0))}},J()),Tf=[!0,T,R],Uf=[!0,T,S],Vf=[!0,T,T];function Wf(a){return function(b){var c=new Mc;hf(b.l,c,Ye(Re,ef,ff,a));Nc(c,c.g.end());b=new Uint8Array(c.h);for(var d=c.i,e=d.length,f=0,g=0;g<e;g++){var h=d[g];b.set(h,f);f+=h.length}c.i=[b];return b}};var Xf=[0,L(function(a,b,c){if(a.h!==1)b=!1;else{var d=a.g;a=nc(d);d=nc(d);O(b,c,ab(a,d));b=!0}return b},function(a,b,c){b=Jd(b);if(b!=null)switch(Tc(b),B(a,c,1),a=a.g,Tc(b),typeof b){case "number":b<0?(c=hb(kb(-b)),b=c.g,z(a,c.h),z(a,b)):(Ua(b),z(a,w),z(a,y));break;case "bigint":c=b<BigInt(0)?hb(wb(-b,fb,kb)):wb(b,fb,kb);b=c.g;z(a,c.h);z(a,b);break;default:c=b.length&&b[0]==="-"?hb(ib(b.substring(1))):ib(b),b=c.g,z(a,c.h),z(a,b)}},J()),-1];var Yf=[0,L(function(a,b,c){if(a.h!==5)return!1;a=a.g;var d=a.h,e=a.g,f=d[e],g=d[e+1],h=d[e+2];d=d[e+3];ic(a,a.g+4);O(b,c,f<<0|g<<8|h<<16|d<<24);return!0},function(a,b,c){b=Gd(b);b!=null&&(B(a,c,5),a=a.g,a.g.push(b>>>0&255),a.g.push(b>>>8&255),a.g.push(b>>>16&255),a.g.push(b>>>24&255))},J()),-1];var Zf=[0,Y,-1,Cf,T,Yf,-1,P,R,Y,Xf,T,Y,-1,[0,Yf,-1],R,Gf,Xf,P,[0,1,R,-4,yf,[0,P,-1,R],T,P,V,[0,Y,R],R,-1,Y,-2,P,-1,Y,P,Y,R,[0,3,R,-1,4,N(function(a,b,c){if(a.h!==2)return!1;a=Kc(a);le(b,b[D]|0,c).push(a);return!0},function(a,b,c){b=K(Kd,b,!1);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&Rc(e,f,ec(g,!0).buffer)}},Je)],yf,X,[0,Y,-1,T],S],T,Qf,V,[0,Xf,V,[0,T,Y],P,Y,-1],1,V,[0,Gf,-1,X],Y,Xf];var $f=[0,Cf,[0,P,T,R,T,R,Hf,Cf,T,R,T,-1,P,R,P],Pf,[0,N(function(a,b,c){if(a.h!==1&&a.h!==2)return!1;b=ke(b,c);if(a.h==2){c=a.g;a=kc(a.g)/8;var d=c.g,e=8*a;if(d+e>c.i)throw Error();var f=c.h;d+=f.byteOffset;vc===void 0&&(vc=(new Uint16Array((new Uint8Array([1,2])).buffer))[0]==513);if(vc)for(c.g+=e,c=new Float64Array(f.buffer.slice(d,d+e)),a=0;a<c.length;a++)b.push(c[a]);else for(e=0;e<a;e++)b.push(pc(c))}else b.push(pc(a.g));return!0},function(a,b,c){b=K(Cd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=
a,f=c,g=b[d];g!=null&&(B(e,f,1),e=e.g,Ya(g),z(e,w),z(e,y))}},Ie),-1]];function we(a){this.l=G(a,void 0,void 0,2048)}p(we,I);function ag(a){a=he(a,1,ne);return a==null?ac():a}function bg(a){var b=16E3;b=b===void 0?0:b;a=Gd(he(a,2));return a!=null?a:b};function cg(a){this.l=G(a,void 0,void 0,2048)}p(cg,I);function dg(a){this.l=G(a,void 0,void 0,2048)}p(dg,I);var eg=[0,Pf,R];var fg=[0,[1,2,3,4],Nf,Rf,W,[0,T,Y],Rf];var gg=[0,T,-2,3,P,T,U,Y,-1,V,fg,T,-2];var hg=[0,R,-3];var ig=[0,[1,2,3,4],Mf,-1,Nf,-1];var kg=[0,T,-1,1,T,-1,6,U,[0,X,T,X,R,X,-4,P,X,P,-1],S,U,-1];var Z=[0,Y,-5];var lg=[0,[0,T,-5,S,U,Z],T,-7,S,T,U,Z];var mg=[0,U,1,Y,-1,T];var ng=[0,T,-2,Z,T];var og=[0,T,-1,S,T,U,Z];var pg=[0,V,[0,T,-1],T,S,T];var qg=[0,T,-2,Z];var rg=[0,T,-3,R,T,S,T,-1,S,T,U,Z,T,-2];var sg=[0,S,T,-3,R,T,S,T,U,Z];var tg=[0,T,-3,R,T,-3,S,T,U,Z];var ug=[0,T,R,Y,T];var vg=[0,T,-2,R,T,S,T,S,U,Z];var wg=[0,T,-2,S];var xg=[0,sg,vg,og,T,R,T,S,T,U,Z];var yg=[0,sg,Cf,T,R,T,S,T,U,Z,T];var zg=[0,T,-1,S,T,U,Z,S];var Ag=[0,T,R,S];var Bg=[0,T,U,T,R,T,S,T,U,Z];var Cg=[0,R,-2,S,T,R,T,R,T,S,T,U,Z,S];var Dg=[0,Y,-1];var Eg=[0,P,-1];var Fg=[0,V,[0,P,-2],P,-1,R,V,[0,R,Y,R,Y,X,Y,-1,V,Eg,[0,P,-1],[0,V,Eg,P,Y],[0,V,Eg,Y]],P];var Gg=[0,P,-2];var Hg=[-11,{},hg,T,[0,Lf,If,Q,U,V,[0,Q],[0,Q]],Q,T,-1,[0,Gg],T,[0,Q,-1,V,[0,Y,R]],-1];var Ig=[0,hg,[0,S,P,Q,-1],R,[0,Q]];var Jg=[0,R,-2];var Kg=[0,Y,[0,Hf,Df]];var Lg=[0,Y,[0,Hf,U]];var Mg=[0,R,-1,Y,R];var Ng=[0,Q,If];var Og=[0,Q,If,T];var Pg=[0,[0,Ff,Y,S]];var Qg=[0,R,-2,T];var Rg=[0,Y];var Tg=[-15,{},V,[-45,{},[1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,21,25,32,36,37,41],Nf,T,W,og,W,zg,W,sg,W,vg,W,Cg,W,xg,W,rg,W,lg,W,Bg,W,yg,W,tg,W,pg,Nf,-1,V,wg,Nf,-1,Fg,Bf,[0,S,-1,Y,Dg,S,-1,P,S,U,Mg,Y,-1],Zf,S,W,[0,T,-1],V,[0,T,-1],[0,U,S],Z,Y,Rg,S,W,Ag,T,U,T,W,qg,W,ng,T,-1,S,W,ug,S,Qg,T],V,[0,T,V,[0,T,-1,Y],V,[0,T,-1],T,Y,[0,Y,-3],U,S,T],4,Rg,P,S,function(){return Sg},T,Pg,S,[0,S,-1]],Sg=[0,V,function(){return Tg},-1];var Ug=function(a,b){return function(c,d){a:{var e={S:!0};d&&Object.assign(e,d);c=Cc(c,void 0,void 0,e);try{var f=new a,g=f.l;bf(b)(g,c);var h=f;break a}catch(k){if(k instanceof RangeError)throw new SyntaxError;throw k;}finally{Ec(c)}h=void 0}return h}}(dg,[0,Y,2,eg,Y,[-500,{},Gf,T,Tg,-1,1,[0,Y,R,-1,P],[0,T,-5,R,T,1,S,-1,T,Y,V,gg,T],Cf,-2,89,[-5,{},V,[-75,{},hg,X,-1,T,Y,T,-2,S,P,Y,T,S,-1,5,og,zg,T,sg,vg,Cg,xg,sg,rg,lg,Bg,yg,tg,T,-1,qg,T,ng,1,pg,ug,[0,T,-1],V,wg,7,kg,1,T,S,T,S,Ag,T,S,T,-2,ig,T,S,P,
U,1,T,S,1,T,mg,Y,S],V,[-71,{},hg,Y,T,-1,S,1,T,Y,kg,P,Y,S,Qf,T,Dg,1,R,S,1,T,Y,P,[0,[0,P,-2],[0,P,-2]],[0,Y,-2],25,Fg,T,3,S,-1,1,S,T,2,S,ig,T,Y,P,T,-1,1,T],V,[-11,{},hg,T,Y,5,[0,R,-3],T],V,[-12,{},hg,T,S,P,-1,[0,P,-6,V,[0,T,Y,P]],Af,R,-1,T,[0,[0,R,-3],V,[0,T,P]]]],1,[0,3,V,[0,V,Jg,Jg],S],3,Mg,Y,-1,1,[-12,{},Mg,Y,-1,[0,Y,2,Y,-1],Y,-1,T,3,[0,S,-2]],39,[0,[0,R,-2,If,-2],Lg,-2,Kg,Lg,-2,Kg,-5],49,[-3,{},[0,V,Hg,[0,V,[0,T,V,[0,R,P,V,[0,R,P,-1,R],S],V,[0,R,P],S,-2]]],V,[0,R,V,[0,hg,[-10,{},R,-2,X,[0,X,-2,
P,-8,Af,-5,Sf,-1],Qf,R,-2],Gg,P,-2,V,[0,Y,Af]]]],[-3,{},[0,V,Hg],V,[-6,{},V,Ig,V,Gg,Hf,Kf,If]],48,[0,[0,V,Ig,$f],[0,P,X,-1,P,X]],49,eg,599,[-1,{}],S,[0,P,-2,R],[-3,{},V,[-7,{},X,-1,S,V,[0,[1,2,3,4],W,[-5,{},Y,T,-1,S],W,[0],W,[0],W,[0]],P,X],X],Ng,V,Og]]);var Vg=Wf(gg);function Wg(a){this.l=G(a,void 0,void 0,2048)}p(Wg,I);var Xg=[1,4];function Yg(a){this.l=G(a,11,void 0,2048)}p(Yg,I);var Zg=[0,R,Pf,Y];var $g=[-11,{},[0,V,[0,Y,1,Y],Qf,Zf,U,V,[0,T,Y,P,Y],1,Y,-1,S],[0,T,-3,P,[0,R,T],Qf,-1],[0,Xg,Bf,[0,Y],[0,2,Y],Rf,[0,S,-1],P,Y,-2],[0,1,P,V,[0,T,-1],Qf,Pg,R],mg,[-1,{}],[0,[1,3],W,[0,[3,4],V,fg,-1,Jf,Mf,V,fg],T,Nf],[0,[1,2,3,4,5,6,7,8,9,10,11],Rf,-10],[0,[1,2],[6],[3,4,5],W,Zg,W,Ng,W,Zg,W,Ng,W,[0,Q],W,[0,R,-1,S,P,-1]],[0,[1],W,Ng,V,Og,Zg]];var ah=[-3,{},T,$g];function bh(a){this.l=G(a,void 0,void 0,2048)}p(bh,I);function ch(a){this.l=G(a,5,void 0,2048)}p(ch,I);function dh(a){this.l=G(a,void 0,void 0,2048)}p(dh,I);var eh=[2,3,4];var fh=[0,T,-2];var gh=[0,[3,4],T,-1,Ef,zf,R,-1,T,-1];var hh=[0,eh,R,W,[-5,{},V,[0,[100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120],R,T,-1,$g,V,[0,[4,5],R,T,-1,Rf,Nf,T,$g,Y],T,-1,Qg,S,90,Nf,W,[0,T,Y,[0,Y,P,Y]],W,[0,T],W,[0,T,R],W,[0,T,Y],W,[0,T,-1],W,[0,T,Y],W,gh,W,[0,1,T],W,fh,W,[0,U,Y],W,[0,[5,6,7],R,-2,T,Rf,-1,Jf],W,[0,[5,6],R,-3,Rf,Jf],W,[0,[1,2],[4,5,6],W,gh,W,fh,T,Rf,-1,Jf],W,[0,[3,4],[8,9,10],R,-1,Jf,Nf,R,Y,T,Rf,-1,Jf],W,[0,T,U,T],W,[0,[4,5,6],gh,T,1,Rf,-1,Jf],W,[0,T,-3,R,T,-2],W,[0,T,Y],W,[0,V,[0,T,-1],T,
S],W,[0,T,-1]],$g,V,[0,R,-1,$g],S],W,ah,W,[0,[1,2],W,Zg,W,[0,T]]];var ih=[0,kf,Uf,kf,Tf,kf,Vf];function jh(a){this.l=G(a,4,void 0,2048)}p(jh,I);var kh=[-4,{},V,hh,$g,ih];function lh(a){this.l=G(a,3,void 0,2048)}p(lh,I);var mh=Wf([-3,{},V,Tg,kh]);function nh(a){a=a===void 0?new AudioContext({sampleRate:24E3}):a;this.h=!1;this.o=[];this.T={};this.M={};this.D={};this.N={};this.C={};this.Z=new TextEncoder;this.W="";this.I=null;this.J=0;this.K=[];this.H=this.u=this.B=this.j=!1;this.v=[];this.L=[];this.A=[];this.i=a;this.G=this.i.createGain()}aa=nh.prototype;
aa.init=function(a){var b=this;return t(function(c){switch(c.g){case 1:if(b.h)return c.return();b.h=!0;b.extensionId=a;return c.h(loadWasmTtsBindings(),2);case 2:return b.g=c.j,c.h(oh(b),3);case 3:return c.h(ph(b),4);case 4:return c.return(qh(b))}})};aa.onLanguageStatusRequest=function(a){var b=this,c,d;return t(function(e){return e.g==1?b.h?e.F(2):e.h(b.init(b.extensionId),2):e.g!=4?(c="offscreenLanguageStatusResponse",d=a,e.h(rh(b,a),4)):e.return({type:c,lang:d,status:e.j})})};
aa.onInstallLanguageRequest=function(a){var b=this,c,d;return t(function(e){return e.g==1?b.h?e.F(2):e.h(b.init(b.extensionId),2):e.g!=4?(c="offscreenLanguageStatusResponse",d=a,e.h(sh(b,a),4)):e.return({type:c,lang:d,status:e.j})})};aa.onUninstallLanguageRequest=function(a){var b=this,c;return t(function(d){if(d.g==1)return b.h?d.F(2):d.h(b.init(b.extensionId),2);if(d.g!=4)return d.h(th(b,a),4);(c=d.j)&&uh(b);return d.return({type:"offscreenLanguageStatusResponse",lang:a,status:"notInstalled"})})};
function th(a,b){var c,d,e,f,g,h;return t(function(k){switch(k.g){case 1:c=vh(a,b),d=!1,e=q(c),f=e.next();case 2:if(f.done){k.F(4);break}g=f.value;wh(a,g);if(!g.remote||g.unloaded){k.F(3);break}h="/voices/"+g.fileId;k.A(5);return k.h(xh(a,h),7);case 7:d=!0;k.B(3);break;case 5:k.v();case 3:f=e.next();k.F(2);break;case 4:return k.return(d)}})}
aa.onStop=function(a){var b=this,c;return t(function(d){if(!b.h)return d.return();yh(b);b.j=!1;b.B=!1;b.u=a;b.m&&(c={command:"clearBuffers"},b.m.port.postMessage(c),b.m.disconnect());for(zh(b);b.L.length>0;)window.clearTimeout(b.L.pop());b.v=[];b.K.length=0;b.I=null;b.J=0;d.C()})};aa.onPause=function(){var a=this;return t(function(b){if(b.g==1){if(!a.h)return b.return();zh(a);a.u=!0;return b.h(a.i.suspend(),2)}a.j=!1;b.C()})};
aa.onResume=function(){var a=this;return t(function(b){if(b.g==1){if(!a.h||a.j)return b.return();a.u=!1;return a.B?b.h(a.i.resume(),2):(a.A.length===0&&Ah(a),b.return(Bh(a)))}a.j=!0;Ch(a);b.C()})};
aa.onSpeak=function(a,b){var c=this,d,e,f,g,h;return t(function(k){switch(k.g){case 1:return c.u=!1,k.h(c.init(c.extensionId),2);case 2:if(!c.g)throw Error("WASM module not initialized.");return b.voiceName?k.h(c.onStop(!1),3):k.return();case 3:c.utterance=a;d=b.voiceName;if(c.W===d){k.F(4);break}k.A(5);return k.h(Dh(c,d,!1),7);case 7:e=c.D[d];if(!e)throw Error("Invalid voice name: "+b.voiceName);f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");if(c.g){var m=Eh(c,g);var n=Eh(c,f),v=c.g._GoogleTtsInit(m,
n);c.g._free(n);c.g._free(m);m=v===1}else m=!1;if(!m)throw Error("Failed to initialize pipeline "+g);k.B(4);break;case 5:return k.v(),k.return(Promise.reject(Error("Voice is not available")));case 4:c.W=d;var x=b.lang;c.extensionId&&x&&chrome.runtime.sendMessage(c.extensionId,{type:"languageUsed",language:x});try{if(x=d,c.g&&a.length){var A=new ch,F=new bh;var C=je(F,2,Ld(a));var M=Ae(A,[C]);var Qb=new Wg,wa=b.rate;var Rb=pe(Qb,1,Xg,Bd(!wa||wa<.1||wa>10?1:wa));var gb=b.pitch;m=je(Rb,6,Bd(gb?Math.pow(2,
(gb-1)*20/12):1));b.volume!==void 0&&b.volume>=0&&(c.G.gain.value=Math.min(Math.max(b.volume,0),1));n=new jh;v=new dh;A=M;A=ye(A);pe(v,2,eh,A);A&&!jd(A)&&ge(v.l);var Sb=Ae(n,[v]);var Lh=new Yg;var Mh=ze(Lh,3,m);var Nh=ze(Sb,2,Mh);var Oh=new lh;var Ph=ze(Oh,2,Nh);var ld=Array.from(new Uint8Array(mh(Ph))),Qh=c.N[x],Rh=new cg;var Sh=je(Rh,1,Ld(Qh));var md=Vg(Sh),nd=c.g._malloc(ld.length);c.g.HEAPU8.set(ld,nd);var od=c.g._malloc(md.length);c.g.HEAPU8.set(md,od);var Th=c.g._GoogleTtsInitBuffered(nd,od,
ld.length,md.length);c.g._free(nd);c.g._free(od);if(!Th)throw Error("Failed to initialize buffered synthesis.");Ah(c)}}catch(jg){return h=jg instanceof Error?jg.message:"",k.return(Promise.reject(Error("Synthesis failed with "+h)))}k.C()}})};
function qh(a){return a.i.audioWorklet.addModule("../streaming_worklet_processor.js").then(function(){a.m=new AudioWorkletNode(a.i,"streaming-worklet-processor");a.m.port.onmessage=function(b){a.utterance&&!a.H&&b.data.type==="empty"&&(Fh(a,{type:"end",charIndex:a.utterance.length}),a.onStop(!1))};a.G.connect(a.i.destination)})}function Eh(a,b){b=a.Z.encode(b+"\x00");var c=a.g._malloc(b.length);a.g.HEAPU8.set(b,c);return c}
function Ah(a){var b=setTimeout(function(){a.H=!0;var c=a.g,d=c._GoogleTtsReadBuffered();if(d===-1)Fh(a,{type:"error"}),yh(a);else{for(var e=c._GoogleTtsGetTimepointsCount(),f=0;f<e;f++)Gh(a,{audioDeltaMillis:c._GoogleTtsGetTimepointsTimeInSecsAtIndex(f)*1E3,charIndex:Number(c._GoogleTtsGetTimepointsCharIndexAtIndex(f)),length:Number(c._GoogleTtsGetTimepointsCharLengthAtIndex(f))});f=c._GoogleTtsGetEventBufferPtr();e=c._GoogleTtsGetEventBufferLen();c=new Uint8Array(c.HEAPU8.buffer,f,e);c=Ug(c.slice(0,
e));d=d===0;e=c.l;ve(e,e[D]|0)!==void 0?Hh(a,c,d):Ih(a,null);d?yh(a):Ah(a)}},0);a.A.push(b)}function yh(a){a.H=!1;a.g._GoogleTtsFinalizeBuffered()}function zh(a){for(;a.A.length>0;)window.clearTimeout(a.A.pop())}function Gh(a,b){var c=b.audioDeltaMillis,d=b.charIndex,e=b.length;d<0||c<=0||(a.j?c<-100||(c<2?Fh(a,{type:"word",charIndex:d,length:e}):(c=window.setTimeout(function(){a.j?Fh(a,{type:"word",charIndex:d,length:e}):a.v.push(b)},c),a.L.push(c))):a.v.push(b))}
function Ch(a){var b=a.v;a.v=[];b=q(b);for(var c=b.next();!c.done;c=b.next())Gh(a,c.value)}function Hh(a,b,c){if(bg(xe(b))===24E3){var d;b=(d=ag(xe(b)))==null?void 0:new Uint8Array(cc(d)||0);d=new Uint8Array(b);d=new Int16Array(d.buffer);d=Float32Array.from(d,function(e){return e/32768});Jh(a,d,c)}}
function Jh(a,b,c){for(var d=a.I,e=a.J,f=0,g=b.length;f<g;){var h=Math.min(128-e,g-f);d||(d=new Float32Array(128));d.set(b.subarray(f,f+h),e);f+=h;e+=h;e===128&&(Ih(a,d),e=0,d=null)}e!==0&&(c?Ih(a,d):(a.I=d,a.J=e))}function Ih(a,b){b&&a.K.push(b);if(a.m)for(;b=a.K.shift();)a.m.port.postMessage({command:"addBuffer",buffer:b}),a.B||a.u||Bh(a)}function Bh(a){return t(function(b){if(b.g==1)return a.m.connect(a.G),b.h(a.i.resume(),2);a.j=!0;a.B=!0;Fh(a,{type:"start",charIndex:0});Ch(a);b.C()})}
function rh(a,b){return t(function(c){return c.return(Kh(a,b,!1))})}function sh(a,b){return t(function(c){return c.return(Kh(a,b,!0))})}function Kh(a,b,c){var d,e,f;return t(function(g){switch(g.g){case 1:return d=vh(a,b),e=d.map(function(h){return Dh(a,h.speakers[0].name,c)}),g.A(2),g.h(Promise.all(e),4);case 4:f="installed";c&&uh(a);g.B(3);break;case 2:g.v(),f=c?"failed":"notInstalled";case 3:return g.return(f)}})}
function vh(a,b){var c=b.toLowerCase();return c.includes("-")?a.o.filter(function(d){var e;return((e=d.language)==null?void 0:e.toLowerCase())===c}):a.o.filter(function(d){var e;return((e=d.language)==null?void 0:e.split("-")[0])===c})}
function Uh(a,b,c){var d,e,f,g,h,k,m,n,v,x;return t(function(A){if(!a.C[b])return A.return(Promise.resolve());d=a.C[b];f=q(Object.entries(a.M));for(g=f.next();!g.done;g=f.next())if(h=g.value,k=q(h),m=k.next().value,n=k.next().value,v=m,x=n,d===x){e=v;break}return e?A.return(Dh(a,e,c)):A.return(Promise.reject(Error("No multivoice found for: "+b)))})}
function Dh(a,b,c){var d,e,f,g,h,k;return t(function(m){switch(m.g){case 1:if(!a.g)return m.return(Promise.reject(Error("WASM module not initialized.")));m.A(2);return m.h(Uh(a,b,c),4);case 4:m.B(3);break;case 2:return d=m.v(),m.return(Promise.reject(Error(""+d)));case 3:e=a.D[b];if(!e)return m.return(Promise.reject(Error("Invalid voice name: "+b)));f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");try{if(h=a.g.FS.stat(g))return m.return(Promise.resolve())}catch(n){}k=a.T[b];return c||k.indexOf("http")!==
0?m.return(fetch(k).then(function(n){return n.ok?n.arrayBuffer():Promise.reject(Error("Failed to fetch voice from url: "+k))}).then(function(n){if(!n)return Promise.reject(Error("Failed to fetch voice from url: "+k));if(!Vh(a,e,n))return Promise.reject(Error("Failed to validate voice data: "+e));try{a.g.FS.stat(f)}catch(F){a.g.FS.mkdir(f)}a.g.FS.stat(f);var v=Eh(a,f),x=new Uint8Array(n),A=a.g._malloc(x.length);a.g.HEAPU8.set(x,A);n=a.g._GoogleTtsInstallVoice(v,A,n.byteLength);a.g._free(v);a.g._free(A);
return n!==1?Promise.reject(Error("Failed to install voice.")):new Promise(function(F,C){a.g.FS.syncfs(!1,function(M){M?C(M):F()})})})):m.return(Promise.reject(Error("Not downloading remote voice because caller did not request it.")))}})}function Fh(a,b){a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenTtsEventResponse",event:b})}
function oh(a){var b,c;return t(function(d){if(d.g==1){if((b=a.g)==null||!b.FS)throw Error("WASM FS not ready for IDBFS setup.");try{a.g.FS.stat("/voices")}catch(e){a.g.FS.mkdir("/voices")}d.A(2);return d.h(new Promise(function(e,f){a.g.FS.mount(a.g.IDBFS,{},"/voices");a.g.FS.syncfs(!0,function(g){g?f(g):e()})}),4)}if(d.g!=2)return d.B(0);c=d.v();throw c;})}
function ph(a){var b,c,d;return t(function(e){switch(e.g){case 1:return e.A(2),e.h(fetch("voices.json"),4);case 4:b=e.j;if(!b.ok)throw Error("Failed to fetch voices.json: "+b.statusText+" ("+b.status+")");return e.h(b.json(),5);case 5:c=e.j;a.o=c;uh(a);e.B(0);break;case 2:throw d=e.v(),d;}})}
function uh(a){a.T={};a.M={};a.D={};a.N={};a.C={};for(var b={},c=q(a.o),d=c.next();!d.done;d=c.next()){d=d.value;for(var e=q(d.speakers),f=e.next();!f.done;f=e.next()){f=f.value;a.M[f.name]=d.id;a.D[f.name]=d.fileId;a.N[f.name]=f.speaker;d.dependentVoiceId&&(a.C[f.name]=d.dependentVoiceId);wh(a,d);a.T[f.name]=d.remote&&d.unloaded?d.url:"/"+d.id+".zvoice";var g=d.id.split("-");if(g.length<2)throw Error("Unexpected voice id format: "+d.id);g=g[0]+"-"+g[1].toUpperCase();d.language=g;d.remote&&d.unloaded||
(b[g]||(b[g]=[]),b[g].push(f.name))}}a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenVoicesResponse",voices:b})}function wh(a,b){try{a.g.FS.stat(["/voices",b.fileId].join("/")),b.unloaded=!1}catch(c){b.unloaded=!0}}
function xh(a,b){if(a.g)try{for(var c=a.g.FS.readdir(b),d=q(c),e=d.next();!e.done;e=d.next()){var f=e.value;f!=="."&&f!==".."&&a.g.FS.unlink(b+"/"+f)}a.g.FS.rmdir(b);return new Promise(function(g,h){a.g.FS.syncfs(!1,function(k){k?h(k):g()})})}catch(g){return Promise.resolve()}}function Vh(a,b,c){var d,e;return t(function(f){if(f.g==1)return f.h(Wh(c),2);d=f.j;e=a.o.find(function(g){return g.fileId===b});return f.return(e!==void 0&&e.sha256Checksum===d&&e.compressedSize===c.byteLength)})}
function Wh(a){var b,c,d,e;return t(function(f){if(f.g==1)return crypto&&crypto.subtle?f.h(crypto.subtle.digest("SHA-256",a),2):f.return("");b=f.j;c="";for(d=0;d<b.byteLength;d++)e=(new Uint8Array(b))[d],c+=Number(e>>4).toString(16),c+=Number(e&15).toString(16);return f.return(c)})}ea.Object.defineProperties(nh.prototype,{voices:{configurable:!0,enumerable:!0,get:function(){return this.o}}});var Xh=new nh,Yh=null;
chrome.runtime.onMessage.addListener(function(a,b,c){Yh||(Yh=Xh.init(b.id));Yh.then(function(){switch(a.type){case "init":Xh.init(b.id);c({result:"Initialized"});break;case "getLanguageStatus":Xh.onLanguageStatusRequest(a.lang).then(c);break;case "installLanguage":Xh.onInstallLanguageRequest(a.lang).then(c);break;case "uninstallLanguage":Xh.onUninstallLanguageRequest(a.lang).then(c);break;case "removeUnusedLanguage":th(Xh,a.lang).then(function(){c({result:"Removed "+a.lang})});break;case "speak":Xh.onSpeak(a.utterance,
a.options);c({result:"Start speaking"});break;case "stop":Xh.onStop(!0);c({result:"Stopped speech"});break;case "pause":Xh.onPause();c({result:"Paused speech"});break;case "resume":Xh.onResume(),c({result:"Resumed speech"})}});return!0});
